# Generated by Django 3.1.1 on 2020-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(default='Rỗng', max_length=100),
        ),
    ]
