# Generated by Django 3.1.1 on 2020-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_callbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NapThe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telco', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=50)),
                ('serial', models.CharField(default='', max_length=50)),
                ('code', models.CharField(default='', max_length=50)),
                ('madonhang', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
