# Generated by Django 3.1.1 on 2020-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_napthe'),
    ]

    operations = [
        migrations.AddField(
            model_name='napthe',
            name='day',
            field=models.DateField(auto_now=True),
        ),
    ]
