# Generated by Django 3.1.1 on 2020-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200927_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='napthe',
            name='trangthai',
            field=models.CharField(default='', max_length=50),
        ),
    ]
