# Generated by Django 3.1.1 on 2020-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_callbackmodel_callback_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isMod',
            field=models.BooleanField(default=False),
        ),
    ]
